apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  ADMIN_DATA_USER: cG9zdGdyZXM=  # "postgres" em base64, ajuste conforme necessário
  ADMIN_DATA_PASSWORD: bXktc2VjcmV0LXB3 # Base64 encoded value of "my-secret-pw", ajuste conforme necessário
